export const products = [
  {
    id: 1,
    title: "گوشی سامسونگ Galaxy S24",
    price: 32000000,
    originalPrice: 38000000,
    discount: 15,
    category: "موبایل",
    image: "/images/samsung-s24.jpg",
    images: [
      "/images/samsung-s24.jpg",
      "/images/samsung-s24.jpg",
      "/images/samsung-s24.jpg",
    ],
    description: "گوشی سامسونگ Galaxy S24 با پردازنده Snapdragon 8 Gen 3، دوربین ۵۰ مگاپیکسل، باتری ۴۰۰۰ میلی‌آمپر و نمایشگر Dynamic AMOLED 6.2 اینچی.",
    specs: {
      "پردازنده": "Snapdragon 8 Gen 3",
      "رم": "8 گیگابایت",
      "حافظه": "256 گیگابایت",
      "دوربین": "50 مگاپیکسل",
      "باتری": "4000 mAh",
      "سیستم عامل": "Android 14",
    },
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    reviews: [
      { id: 1, user: "علی رضایی", rating: 5, comment: "عالیه، سرعتش خیلی خوبه و دوربینش فوق‌العاده‌ست", date: "1403/03/10" },
      { id: 2, user: "مریم احمدی", rating: 4, comment: "کیفیت خوبیه ولی قیمتش یکم بالاست", date: "1403/02/25" },
      { id: 3, user: "حسین کریمی", rating: 5, comment: "بهترین گوشی که تا حالا داشتم", date: "1403/02/18" },
      { id: 4, user: "زهرا موسوی", rating: 4, comment: "طراحی شیک و باتری خوب داره", date: "1403/01/30" },
      { id: 5, user: "محمد نجفی", rating: 3, comment: "خوبه ولی انتظار داشتم بهتر باشه", date: "1403/01/15" },
      { id: 6, user: "فاطمه صادقی", rating: 5, comment: "خیلی راضیم، سریع ارسال شد", date: "1402/12/20" },
    ],
  },
  {
    id: 2,
    title: "لپ‌تاپ اپل MacBook Air M3",
    price: 85000000,
    originalPrice: 95000000,
    discount: 10,
    category: "لپ‌تاپ",
    image: "/images/macbook-air.jpg",
    images: [
      "/images/macbook-air.jpg",
      "/images/macbook-air.jpg",
    ],
    description: "مک‌بوک ایر با تراشه M3 اپل، باتری ۱۸ ساعته، نمایشگر Liquid Retina 13.6 اینچ و وزن فوق‌العاده سبک.",
    specs: {
      "پردازنده": "Apple M3",
      "رم": "8 گیگابایت",
      "حافظه": "256 گیگابایت SSD",
      "نمایشگر": "13.6 اینچ Retina",
      "باتری": "18 ساعت",
      "سیستم عامل": "macOS Sonoma",
    },
    rating: 4.8,
    reviewCount: 74,
    inStock: true,
    reviews: [
      { id: 1, user: "سارا حسینی", rating: 5, comment: "باتریش واقعاً ۱۸ ساعته، شوکه شدم", date: "1403/03/05" },
      { id: 2, user: "امیر تهرانی", rating: 5, comment: "بهترین لپ‌تاپ برای برنامه‌نویسی", date: "1403/02/20" },
      { id: 3, user: "نیلوفر رستمی", rating: 4, comment: "سبک و قوی، فقط قیمتش زیاده", date: "1403/01/10" },
    ],
  },
  {
    id: 3,
    title: "هدفون Sony WH-1000XM5",
    price: 12500000,
    originalPrice: 15000000,
    discount: 17,
    category: "هدفون",
    image: "/images/sony-headphone.jpg",
    images: ["/images/sony-headphone.jpg"],
    description: "هدفون بی‌سیم سونی با بهترین حذف نویز در کلاس خود، باتری ۳۰ ساعته و کیفیت صدای استودیویی.",
    specs: {
      "نوع": "Over-Ear بی‌سیم",
      "حذف نویز": "ANC پیشرفته",
      "باتری": "30 ساعت",
      "بلوتوث": "5.2",
      "وزن": "250 گرم",
    },
    rating: 4.7,
    reviewCount: 210,
    inStock: true,
    reviews: [
      { id: 1, user: "کیان مرادی", rating: 5, comment: "حذف نویزش فوق‌العاده‌ست، توی مترو مثل یه دنیای دیگه‌ست", date: "1403/03/01" },
      { id: 2, user: "ریحانه کمالی", rating: 5, comment: "صدای خیلی خوبی داره و راحته", date: "1403/02/15" },
      { id: 3, user: "بهزاد اکبری", rating: 4, comment: "عالیه فقط کیف حملش کوچیکه", date: "1403/01/20" },
      { id: 4, user: "مینا فرهادی", rating: 5, comment: "ارزش قیمتشو داره صد در صد", date: "1402/12/10" },
      { id: 5, user: "رضا شریفی", rating: 4, comment: "بسیار خوب، پیشنهاد می‌کنم", date: "1402/11/25" },
      { id: 6, user: "لیلا نوروزی", rating: 3, comment: "خوبه ولی انتظار بیشتری داشتم", date: "1402/11/10" },
    ],
  },
  {
    id: 4,
    title: "ساعت هوشمند Apple Watch Series 9",
    price: 18000000,
    originalPrice: 18000000,
    discount: 0,
    category: "ساعت",
    image: "/images/apple-watch.jpg",
    images: ["/images/apple-watch.jpg"],
    description: "اپل واچ سری ۹ با تراشه S9، صفحه Always-On Retina، پایش سلامت پیشرفته و مقاومت در برابر آب تا ۵۰ متر.",
    specs: {
      "تراشه": "Apple S9",
      "نمایشگر": "Always-On Retina LTPO",
      "مقاومت آب": "50 متر",
      "باتری": "18 ساعت",
      "سیستم عامل": "watchOS 10",
    },
    rating: 4.6,
    reviewCount: 95,
    inStock: true,
    reviews: [
      { id: 1, user: "دانیال صفری", rating: 5, comment: "بهترین ساعت هوشمند بازاره", date: "1403/02/28" },
      { id: 2, user: "آزاده قاسمی", rating: 4, comment: "خیلی کاربردیه، سلامتمو رصد می‌کنه", date: "1403/02/01" },
    ],
  },
  {
    id: 5,
    title: "دوربین Sony Alpha A7 IV",
    price: 120000000,
    originalPrice: 130000000,
    discount: 8,
    category: "دوربین",
    image: "/images/sony-camera.jpg",
    images: ["/images/sony-camera.jpg"],
    description: "دوربین میرورلس فول‌فریم سونی با سنسور ۳۳ مگاپیکسل، فیلمبرداری 4K 60fps و سیستم فوکوس خودکار پیشرفته.",
    specs: {
      "سنسور": "33 مگاپیکسل Full-Frame",
      "فیلمبرداری": "4K 60fps",
      "فوکوس": "Real-time AF",
      "باتری": "580 شات",
      "وزن": "659 گرم",
    },
    rating: 4.9,
    reviewCount: 43,
    inStock: true,
    reviews: [
      { id: 1, user: "پیمان نادری", rating: 5, comment: "حرفه‌ای‌ترین دوربینی که تا حالا کار کردم باهاش", date: "1403/03/08" },
      { id: 2, user: "شیوا رحیمی", rating: 5, comment: "کیفیت عکساش بی‌نظیره", date: "1403/02/10" },
      { id: 3, user: "امین غفاری", rating: 4, comment: "عالیه ولی سنگینه", date: "1403/01/05" },
    ],
  },
  {
    id: 6,
    title: "تی‌شرت اسپرت نایک",
    price: 850000,
    originalPrice: 1200000,
    discount: 29,
    category: "پوشاک",
    image: "/images/nike-shirt.jpg",
    images: ["/images/nike-shirt.jpg"],
    description: "تی‌شرت ورزشی نایک با پارچه Dri-FIT که رطوبت را از پوست دور می‌کند. مناسب برای ورزش و فعالیت‌های روزانه.",
    specs: {
      "جنس": "100% پلی‌استر Dri-FIT",
      "سایزبندی": "S, M, L, XL, XXL",
      "رنگ": "مشکی، سفید، آبی",
      "قابل شستشو": "در ماشین لباسشویی",
    },
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
    reviews: [
      { id: 1, user: "نوید صالحی", rating: 4, comment: "کیفیت خوبیه و سایزبندی درسته", date: "1403/03/12" },
      { id: 2, user: "ترانه ولی‌زاده", rating: 5, comment: "خیلی راحته برای ورزش", date: "1403/02/22" },
      { id: 3, user: "سینا محمودی", rating: 4, comment: "پارچه‌اش خوبه و زود خشک می‌شه", date: "1403/01/18" },
      { id: 4, user: "مهسا کوهی", rating: 3, comment: "معمولیه، انتظار بیشتری داشتم از نایک", date: "1402/12/15" },
      { id: 5, user: "فرهاد عزیزی", rating: 5, comment: "بهترین انتخاب برای ورزش", date: "1402/11/20" },
    ],
  },
  {
    id: 7,
    title: "هدفون Sony WH-1000XM5",
    price: 12500000,
    originalPrice: 15000000,
    discount: 17,
    category: "هدفون",
    image: "/images/sony-headphone.jpg",
    images: ["/images/sony-headphone.jpg"],
    description: "هدفون بی‌سیم سونی با بهترین حذف نویز در کلاس خود، باتری ۳۰ ساعته و کیفیت صدای استودیویی.",
    specs: {
      "نوع": "Over-Ear بی‌سیم",
      "حذف نویز": "ANC پیشرفته",
      "باتری": "30 ساعت",
      "بلوتوث": "5.2",
      "وزن": "250 گرم",
    },
    rating: 4.7,
    reviewCount: 210,
    inStock: true,
    reviews: [
      { id: 1, user: "کیان مرادی", rating: 5, comment: "حذف نویزش فوق‌العاده‌ست، توی مترو مثل یه دنیای دیگه‌ست", date: "1403/03/01" },
      { id: 2, user: "ریحانه کمالی", rating: 5, comment: "صدای خیلی خوبی داره و راحته", date: "1403/02/15" },
      { id: 3, user: "بهزاد اکبری", rating: 4, comment: "عالیه فقط کیف حملش کوچیکه", date: "1403/01/20" },
      { id: 4, user: "مینا فرهادی", rating: 5, comment: "ارزش قیمتشو داره صد در صد", date: "1402/12/10" },
      { id: 5, user: "رضا شریفی", rating: 4, comment: "بسیار خوب، پیشنهاد می‌کنم", date: "1402/11/25" },
      { id: 6, user: "لیلا نوروزی", rating: 3, comment: "خوبه ولی انتظار بیشتری داشتم", date: "1402/11/10" },
    ],
  },
  {
    id: 8,
    title: "ساعت هوشمند Apple Watch Series 9",
    price: 18000000,
    originalPrice: 18000000,
    discount: 0,
    category: "ساعت",
    image: "/images/apple-watch.jpg",
    images: ["/images/apple-watch.jpg"],
    description: "اپل واچ سری ۹ با تراشه S9، صفحه Always-On Retina، پایش سلامت پیشرفته و مقاومت در برابر آب تا ۵۰ متر.",
    specs: {
      "تراشه": "Apple S9",
      "نمایشگر": "Always-On Retina LTPO",
      "مقاومت آب": "50 متر",
      "باتری": "18 ساعت",
      "سیستم عامل": "watchOS 10",
    },
    rating: 4.6,
    reviewCount: 95,
    inStock: false,
    reviews: [
      { id: 1, user: "دانیال صفری", rating: 5, comment: "بهترین ساعت هوشمند بازاره", date: "1403/02/28" },
      { id: 2, user: "آزاده قاسمی", rating: 4, comment: "خیلی کاربردیه، سلامتمو رصد می‌کنه", date: "1403/02/01" },
    ],
  },
  {
    id: 9,
    title: "دوربین Sony Alpha A7 IV",
    price: 120000000,
    originalPrice: 130000000,
    discount: 8,
    category: "دوربین",
    image: "/images/sony-camera.jpg",
    images: ["/images/sony-camera.jpg"],
    description: "دوربین میرورلس فول‌فریم سونی با سنسور ۳۳ مگاپیکسل، فیلمبرداری 4K 60fps و سیستم فوکوس خودکار پیشرفته.",
    specs: {
      "سنسور": "33 مگاپیکسل Full-Frame",
      "فیلمبرداری": "4K 60fps",
      "فوکوس": "Real-time AF",
      "باتری": "580 شات",
      "وزن": "659 گرم",
    },
    rating: 4.9,
    reviewCount: 43,
    inStock: true,
    reviews: [
      { id: 1, user: "پیمان نادری", rating: 5, comment: "حرفه‌ای‌ترین دوربینی که تا حالا کار کردم باهاش", date: "1403/03/08" },
      { id: 2, user: "شیوا رحیمی", rating: 5, comment: "کیفیت عکساش بی‌نظیره", date: "1403/02/10" },
      { id: 3, user: "امین غفاری", rating: 4, comment: "عالیه ولی سنگینه", date: "1403/01/05" },
    ],
  },
  {
    id: 10,
    title: "تی‌شرت اسپرت نایک",
    price: 850000,
    originalPrice: 1200000,
    discount: 29,
    category: "پوشاک",
    image: "/images/nike-shirt.jpg",
    images: ["/images/nike-shirt.jpg"],
    description: "تی‌شرت ورزشی نایک با پارچه Dri-FIT که رطوبت را از پوست دور می‌کند. مناسب برای ورزش و فعالیت‌های روزانه.",
    specs: {
      "جنس": "100% پلی‌استر Dri-FIT",
      "سایزبندی": "S, M, L, XL, XXL",
      "رنگ": "مشکی، سفید، آبی",
      "قابل شستشو": "در ماشین لباسشویی",
    },
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
    reviews: [
      { id: 1, user: "نوید صالحی", rating: 4, comment: "کیفیت خوبیه و سایزبندی درسته", date: "1403/03/12" },
      { id: 2, user: "ترانه ولی‌زاده", rating: 5, comment: "خیلی راحته برای ورزش", date: "1403/02/22" },
      { id: 3, user: "سینا محمودی", rating: 4, comment: "پارچه‌اش خوبه و زود خشک می‌شه", date: "1403/01/18" },
      { id: 4, user: "مهسا کوهی", rating: 3, comment: "معمولیه، انتظار بیشتری داشتم از نایک", date: "1402/12/15" },
      { id: 5, user: "فرهاد عزیزی", rating: 5, comment: "بهترین انتخاب برای ورزش", date: "1402/11/20" },
    ],
  },
];
