import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa" className="font-(--font-vazir)">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
